### ISSUE TITLE
Alma People Job failing

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lib_jobs#923]
### Expected behavior
Alma People Job does not fail

### Actual behavior
It has been failing since #921 was merged

### Impact of this bug

New patrons can't use Alma; former patrons who should no longer have access may still have it.

### Honeybadger link and code snippet, if applicable

[Honeybadger link](https://app.honeybadger.io/projects/100710/faults/121287708)

```
NoMethodError: undefined method 'empty?' for nil

      return "" if oit_people.empty?
                             ^^^^^^^
```
