### PR TITLE
[#923] Handle cases where oit_people is nil, rather than an empty array

### LINKED ISSUE #923: Alma People Job failing
### Expected behavior
Alma People Job does not fail

### Actual behavior
It has been failing since #921 was merged

### Impact of this bug

New patrons can't use Alma; former patrons who should no longer have access may still have it.

### Honeybadger link and code snippet, if applicable

[Honeybadger link](https://app.honeybadger.io/projects/100710/faults/121287708)

```
NoMethodError: undefined method 'empty?' for nil

      return "" if oit_people.empty?
                             ^^^^^^^
```

### PR DESCRIPTION
**Pull request by sandbergja**
Closes #923

### CODE REVIEW

**Review by christinach — APPROVED** [review]
Thanks @sandbergja !
